#!/usr/bin/env php
<?php declare(strict_types=1);

use TinyFramework\Console\ConsoleKernel;
use TinyFramework\Core\Container;

define('TINYFRAMEWORK_START', microtime(true));
define('ROOT', __DIR__);
chdir(ROOT);
require_once 'vendor/autoload.php';

/** @var ConsoleKernel $console */
$console = Container::instance()->get(ConsoleKernel::class);
$exitCode = $console->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput(),
    $output = new Symfony\Component\Console\Output\ConsoleOutput()
);
exit($exitCode);

//exit(\TinyFramework\Shell\Shell::shell());
