name: "CI"

on:
  pull_request: ~
  workflow_dispatch: ~
  push:
    branches:
      - "master"

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

jobs:
  tests:
    name: "Tests"
    runs-on: "ubuntu-latest"
    steps:

      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v3"

      - name: "Build Docker images"
        uses: "docker/bake-action@v6"
        env:
          _UID: 1001
          _GID: 118
        with:
          pull: true
          load: true
          files: |
            docker-compose.yaml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max

      - name: "start docker container"
        env:
          _UID: 1001
          _GID: 118
        run: "docker compose up --wait --no-build -d"

      - name: "composer install"
        run: "docker exec tinyframework-php-1 composer install"

      - name: "Run parallel-lint"
        run: "docker exec tinyframework-php-1 vendor/bin/parallel-lint --no-colors --no-progress --show-deprecated src/ tests/"

      - name: "Run phpstan"
        run: "docker exec tinyframework-php-1 vendor/bin/phpstan analyse --error-format=md --no-progress > .reports/phpstan.md"
        continue-on-error: true

      - name: "Run phpunit"
        env:
          XDEBUG_MODE: coverage
        run: "docker exec tinyframework-php-1 vendor/bin/phpunit --coverage-clover .reports/clover.xml"
        continue-on-error: true

      - name: "Run SBOM"
        run: "docker exec tinyframework-php-1 composer CycloneDX:make-sbom --output-format=xml --output-file=.reports/sbom.xml --omit=dev"
        continue-on-error: true

      - name: "stop docker container"
        run: "docker compose stop"

      - name: "Coverage Check"
        uses: "ericsizemore/phpunit-coverage-check-action@1.0.0"
        with:
          clover_file: '.reports/clover.xml'
          threshold: 100

      - name: "Archive reports artifacts"
        uses: "actions/upload-artifact@v4"
        with:
          name: "Reports"
          path: |
            .reports
